// ============================================================
// FORGE OS — PILOT CONFIGURATION  (E6 Alpha Activation)
//
// The first real manufacturing participant. Everything in this file was
// SUPPLIED, not derived: each field below traces to an explicit statement from
// the pilot configuration, and any field that was not supplied is null rather
// than filled in.
//
// WHAT WAS SUPPLIED
//   organisation    SOLC
//   forge_role      sme
//   hub             warri
//   component       the existing wheel hub — FTT-HB-001, class wheel-hub
//   mission         FORGE-HUB
//
// WHAT WAS NOT SUPPLIED, AND IS THEREFORE NULL
//   legal name, RC number, state, city, website, description, verification
//   evidence, machine registry, capability declaration, and the component
//   INSTANCE identifier.
//
// THE WHEEL DISC QUESTION, RESOLVED EXPLICITLY.
// The pilot was first described as a "Wheel Disc". No wheel disc existed in this
// repository — zero occurrences — and a pressed wheel disc is not a machined
// wheel hub, so the two were never treated as equivalent. The configuration was
// then ratified as the EXISTING wheel hub: specification FTT-HB-001 "Wheel hub,
// machined billet", class wheel-hub, mission FORGE-HUB. That ratification is
// recorded here because it is the reason this file names a hub, and a later
// reader must be able to see that the substitution was decided rather than
// assumed. `assertPilotIntegrity()` below fails loudly if the mapping ever
// drifts. No wheel-disc class was created, because no wheel disc is being made.
//
// THE COMPONENT INSTANCE IS NOT CONFIGURED HERE, ON PURPOSE.
// A specification is a drawing and a class is a category — both are master data
// and both were supplied. A component INSTANCE is a physical object that exists
// in a workshop, and no instance identifier was supplied. Inventing one would
// mean this file asserting that a particular part exists. It is therefore null,
// and the operator names the part at the moment they record a fact about it —
// which is the only moment anyone actually knows it.
//
// DATABASE IDENTITY vs EVENT IDENTITY.
// `organisations.id` is a uuid generated by Postgres, so it cannot appear in
// source (Part 3 forbids hardcoding it, and it differs per deployment). Events
// therefore carry the stable configuration id below, and the database row is
// matched to it by NAME. That seam is deliberate and narrow; it closes when
// organisations are read from the table rather than declared — TRANSITIONAL.md D2.
// ============================================================

import { PROVENANCE, COMPONENT_CLASS, classForSpecification } from "./network.js";

// ---------- PILOT ORGANISATIONS ----------
// `role` is a forge_role enum value from supabase/migrations/002_identity.sql.
// `verification` is "unverified" because verification is earned, never assumed
// on admission — being the pilot is not being verified.
export const PILOT_ORGANISATIONS = Object.freeze([
  Object.freeze({
    id: "SOLC",
    name: "SOLC",
    role: "sme",
    // `hubs` is an array to match the seed organisation shape exactly, so one
    // reader serves both registries and no surface needs to know which it holds.
    hubs: Object.freeze(["warri"]),
    provenance: PROVENANCE.PILOT,
    verification: "unverified",
    // Supplied by nobody. Left absent so no surface can render a guess.
    rcNumber: null, state: null, city: null, website: null, description: null,
  }),
]);

// ---------- PILOT ASSIGNMENTS ----------
// "This organisation is admitted to record facts about this component class,
// against this specification, at this hub, under this mission."
//
// An assignment is NOT a capability claim and NOT a responsibility claim.
// Capability lives in network.js and says what an organisation CAN make.
// Responsibility lives in the event fold and says who IS accountable for a
// specific instance. An assignment only says which facts the pilot is admitted
// to state; responsibility still arrives the way it always did, on an event.
export const PILOT_ASSIGNMENTS = Object.freeze([
  Object.freeze({
    organisation: "SOLC",
    specification: "FTT-HB-001",
    componentClass: COMPONENT_CLASS.WHEEL_HUB,
    hub: "warri",
    mission: "FORGE-HUB",
    // UNKNOWN by construction — see the header. The operator supplies it.
    component: null,
    provenance: PROVENANCE.PILOT,
  }),
]);

// ---------- READERS ----------
export const pilotOrganisationById = (id) =>
  PILOT_ORGANISATIONS.find((o) => o.id === id) ?? null;

/**
 * The database↔configuration join. Matching is by name because the uuid cannot
 * live in source. Comparison is trimmed and case-insensitive so " solc " typed
 * at registration still resolves; it is otherwise exact, because a fuzzy match
 * here would admit an organisation the configuration never named.
 */
export const pilotOrganisationByName = (name) => {
  if (typeof name !== "string") return null;
  const k = name.trim().toLowerCase();
  if (!k) return null;
  return PILOT_ORGANISATIONS.find((o) => o.name.trim().toLowerCase() === k) ?? null;
};

export const isPilotOrganisation = (id) => pilotOrganisationById(id) !== null;

/** Every assignment held by an organisation. Empty means none — never a default. */
export const assignmentsOf = (organisationId) =>
  PILOT_ASSIGNMENTS.filter((a) => a.organisation === organisationId);

/**
 * The single assignment an organisation holds, or null.
 *
 * Returns null when there is more than one rather than picking the first. If a
 * pilot ever holds two assignments, the caller has to decide which is meant,
 * and silently choosing would attribute work to the wrong specification.
 */
export const assignmentFor = (organisationId) => {
  const all = assignmentsOf(organisationId);
  return all.length === 1 ? all[0] : null;
};

/**
 * Provenance across BOTH registries.
 *
 * Returns null for an organisation no registry knows. That is the important
 * case: absence is UNKNOWN, and UNKNOWN must never be rendered as real. This
 * function is the only place a surface should ask, so that seed and pilot can
 * never be confused for one another or for a verified member.
 */
export const provenanceOfOrganisation = (id, seedOrganisations = []) => {
  const pilot = pilotOrganisationById(id);
  if (pilot) return pilot.provenance;
  const seed = seedOrganisations.find((o) => o.id === id);
  return seed ? seed.provenance : null;
};

/**
 * INTEGRITY GUARD — fails loudly if the pilot component identity drifts.
 *
 * Three ways this configuration could quietly become untrue, all checked:
 *   1. the specification stops mapping to the class named here
 *   2. the class named here disappears from the taxonomy
 *   3. someone introduces a wheel-disc identifier and points the pilot at it
 *
 * (3) matters most. The pilot was described as a disc and ratified as a hub; the
 * only thing keeping that honest is that nothing may later relabel it. Called by
 * the pilot test suite, so a drift breaks the build rather than a demonstration.
 */
export function pilotIntegrityProblems(
  organisations = PILOT_ORGANISATIONS,
  assignments = PILOT_ASSIGNMENTS,
) {
  const problems = [];
  const classes = new Set(Object.values(COMPONENT_CLASS));
  const orgById = (id) => organisations.find((o) => o.id === id) ?? null;

  for (const a of assignments) {
    const org = orgById(a.organisation);
    if (!org) {
      problems.push(`assignment names unknown pilot organisation "${a.organisation}"`);
    } else if (!org.hubs.includes(a.hub)) {
      // The assignment's hub is WHERE this work happens; the organisation's hubs
      // are where it operates. They may legitimately differ in future, but a
      // mismatch today would mean one of the two was invented.
      problems.push(
        `assignment places "${a.organisation}" at hub "${a.hub}", which is not among its hubs (${org.hubs.join(", ") || "none"})`
      );
    }
    if (!classes.has(a.componentClass)) {
      problems.push(`assignment names unknown component class "${a.componentClass}"`);
    }
    const mapped = classForSpecification(a.specification);
    if (mapped !== a.componentClass) {
      problems.push(
        `specification "${a.specification}" maps to "${mapped}" but the assignment claims "${a.componentClass}"`
      );
    }
    if (/disc/i.test(a.specification) || /disc/i.test(a.componentClass)) {
      problems.push(
        `assignment references a wheel disc ("${a.specification}" / "${a.componentClass}"). ` +
        `The pilot was ratified as the machined wheel hub FTT-HB-001. A disc is a ` +
        `different part and needs its own specification, class and drawing.`
      );
    }
  }

  for (const o of organisations) {
    if (o.provenance !== PROVENANCE.PILOT) {
      problems.push(`pilot organisation "${o.id}" carries provenance "${o.provenance}"`);
    }
    if (o.verification === "verified") {
      problems.push(`pilot organisation "${o.id}" claims verification it has not been granted`);
    }
  }

  return problems;
}

/** Throws on any integrity problem in the SHIPPED configuration. */
export function assertPilotIntegrity() {
  const problems = pilotIntegrityProblems();
  if (problems.length) {
    throw new Error(`Pilot configuration integrity failure:\n  - ${problems.join("\n  - ")}`);
  }
  return true;
}

export default {
  PILOT_ORGANISATIONS, PILOT_ASSIGNMENTS,
  pilotOrganisationById, pilotOrganisationByName, isPilotOrganisation,
  assignmentsOf, assignmentFor, provenanceOfOrganisation,
  pilotIntegrityProblems, assertPilotIntegrity,
};
